### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "muhammed@example.com",
  "password": "password$",
  "username": "x14Kernal",
  "displayName": "Muhammed Ahmed"
}

### Login with email
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "identifier": "muhammed@example.com",
  "password": "password$"
}

### Login with username
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "identifier": "x14kernal",
  "password": "password$"
}

### Get current authenticated user
GET http://localhost:3000/api/auth/me

### Login with invalid identifier
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "identifier": "blablabla@example.com",
  "password": "password$"
}

### Login with invalid password
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "identifier": "x14kernal",
  "password": "invalid-password"
}

### Logout
POST http://localhost:3000/api/auth/logout


### Get all user's sessions
GET http://localhost:3000/api/sessions

### Delete user's session
DELETE  http://localhost:3000/api/sessions/882a2841-4a2a-41c6-b2c7-197c71224eed

### Get all bookmarks
GET http://localhost:3000/api/bookmarks

### Get all recipes
GET http://localhost:3000/api/recipes

### Get all my recipes
GET http://localhost:3000/api/recipes/mine

### Get my recipes with tag 'dinner'
GET http://localhost:3000/api/recipes/mine?tags=dinner

### Get one of my recipe (public one)
GET http://localhost:3000/api/recipes/mine/abba74bc-a409-49d1-9183-aae4bf6d8821

### Get one of my recipe (private one)
GET http://localhost:3000/api/recipes/mine/b6f72f48-0c5d-4629-8a0a-1062f6606529

### Try to get a recipe not mine
GET http://localhost:3000/api/recipes/mine/dcb4a8bb-ab59-4f9a-ab5f-ae015fdf69a0

### Try to get one of my trashed recipe (through mine endpoint) -> Not Found
GET http://localhost:3000/api/recipes/mine/29a0ca1b-0fb5-410d-b08f-839028fba9a5

### Try to get one of my public trashed recipe (through trash endpoint)
GET http://localhost:3000/api/recipes/trash/29a0ca1b-0fb5-410d-b08f-839028fba9a5

### Try to trash one of recipe
PATCH  http://localhost:3000/api/recipes/29a0ca1b-0fb5-410d-b08f-839028fba9a5/trash

### Try to restore one of my trashed recipe
PATCH  http://localhost:3000/api/recipes/29a0ca1b-0fb5-410d-b08f-839028fba9a5/restore

### Try to bookmark a recipe
POST   http://localhost:3000/api/recipes/4fb5e7b2-81cd-4ea4-b94f-ac5a37e9cfe3/bookmark

### Try to remove recipe form bookmarks
DELETE    http://localhost:3000/api/recipes/29a0ca1b-0fb5-410d-b08f-839028fba9a5/bookmark

### Try to get one of my private trashed recipe (through trash endpoint)
GET http://localhost:3000/api/recipes/trash/63a850dd-462a-4937-bc10-4525e443d923

### Get recipes with tag 'mexican'
GET http://localhost:3000/api/recipes?tags=mexican

### Get recipes with tags 'mexican' or 'italian'
GET http://localhost:3000/api/recipes?tags=mexican,italian&ingredients=Cilantro

### Get recipes with ingredient 'Cilantro'
GET http://localhost:3000/api/recipes?ingredients=Cilantro

### Get recipes with ingredients 'Cilantro' and 'lime'
GET http://localhost:3000/api/recipes?ingredients=Cilantro,lime

### Get recipes with tags 'mexican' or 'italian' AND ingredients 'Cilantro'
GET http://localhost:3000/api/recipes?tags=mexican,italian&ingredients=Cilantro

### Get recipes with tags 'not-exist'
GET http://localhost:3000/api/recipes?tags=not-exist

### Get recipes with ingredients 'not-exist'
GET http://localhost:3000/api/recipes?ingredients=not-exist

### Get recipes page & limit & title & search
GET http://localhost:3000/api/recipes?page=1&limit=3&sortBy=title&search=creamy
### Get recipe with id a8e6c368-b466-4682-8db5-1dd8eca3f800
GET http://localhost:3000/api/recipes/a8e6c368-b466-4682-8db5-1dd8eca3f800

### Get a random recipe
GET http://localhost:3000/api/recipes/random


### Post a new recipe
POST http://localhost:3000/api/recipes
Content-Type: application/json

{
  "title": "Creamy Garlic Chicken",
  "servingSize": 4,
  "visibility": "public",
  "images": [
    {
      "imageUrl": "https://example.com/images/creamy-garlic-chicken.jpg"
    }
  ],
  "steps": [
    {
      "description": "Cut the chicken breast into bite-sized pieces.",
      "image": null
    },
    {
      "description": "Heat the olive oil in a large pan over medium-high heat and cook the chicken until golden.",
      "image": null
    },
    {
      "description": "Add the minced garlic and cook for about one minute until fragrant.",
      "image": null
    },
    {
      "description": "Pour in the heavy cream and simmer for five minutes until the sauce thickens.",
      "image": null
    }
  ],
  "ingredients": [
    {
      "name": "Chicken Breast",
      "image": null,
      "quantity": 500,
      "unit": "g"
    },
    {
      "name": "Olive Oil",
      "image": null,
      "quantity": 2,
      "unit": "tbsp"
    },
    {
      "name": "Garlic",
      "image": null,
      "quantity": 3,
      "unit": "cloves"
    },
    {
      "name": "Heavy Cream",
      "image": null,
      "quantity": 200,
      "unit": "ml"
    }
  ],
  "tags": [
    {
      "name": "Dinner"
    },
    {
      "name": "Chicken"
    },
    {
      "name": "Baking"
    },
    {
      "name": "Easy"
    }
  ]
}

### Update recipe with id=a8e6c368-b466-4682-8db5-1dd8eca3f800
PATCH http://localhost:3000/api/recipes/a8e6c368-b466-4682-8db5-1dd8eca3f800
Content-Type: application/json

{
  "title": "Creamy Garlic Chicken",
  "servingSize": 8,
  "visibility": "public",
  "images": [
    {
      "imageUrl": "https://example.com/images/creamy-garlic-chicken-updated.jpg"
    }
  ],
  "steps": [
    {
      "description": "Updated Cut the chicken breast into bite-sized pieces.",
      "image": null
    },
    {
      "description": "Heat the olive oil in a large pan over medium-high heat and cook the chicken until golden.",
      "image": null
    },
    {
      "description": "Add the minced garlic and cook for about one minute until fragrant.",
      "image": null
    }
  ],
  "ingredients": [
    {
      "name": "Egyptian Olive Oil",
      "image": null,
      "quantity": 2,
      "unit": "tbsp"
    },
    {
      "name": "Garlic",
      "image": null,
      "quantity": 3,
      "unit": "cloves"
    },
    {
      "name": "Heavy Cream",
      "image": null,
      "quantity": 200,
      "unit": "ml"
    }
  ],
  "tags": [
    {
      "name": "Chicken"
    },
    {
      "name": "Baking"
    },
    {
      "name": "Easy"
    }
  ]
}

 
### Delete recipe with id=19
DELETE http://localhost:3000/api/recipes/68c2fdf2-d114-4ba7-ab7e-6824a62e5e6f