### Get all recipes
GET http://localhost:3000/api/recipes

### Get recipes with tag 'mexican'
GET http://localhost:3000/api/recipes?tag=mexican

### Get recipes with ingredient 'eggs'
GET http://localhost:3000/api/recipes?ingredient=eggs

### Get recipes with ingredient 'cilantro' and tag 'mexican'
GET http://localhost:3000/api/recipes?ingredient=cilantro&tag=mexican

### Get recipes with tag 'not-exist'
GET http://localhost:3000/api/recipes?tag=not-exist

### Get recipe with id 10000000-0000-0000-0000-000000000001
GET http://localhost:3000/api/recipes/10000000-0000-0000-0000-000000000001

### Get a random recipe
GET http://localhost:3000/api/recipes/random

### Post a new recipe
POST http://localhost:3000/api/recipes
Content-Type: application/json

{
  "title": "Classic Pan 2",
  "ingredients": [
    "Flour",
    "Flour",
    "Baking powder",
    "Baking powder"
  ],
  "steps": [
    "Mix",
    "Serve"
  ],
  "tags": [
    "Hreakfast",
    "Healthy",
    "Random Tag"
  ]
}

### Update recipe with id=20
PATCH  http://localhost:3000/api/recipes/10000000-0000-0000-0000-000000000001
Content-Type: application/json

{
  "user_id":"11111111-1111-1111-1111-111111111111",
  "title": "Lentil Soup updated",
  "ingredients": [
    "Red lentils",
    "Onion",
    "Vegetable broth"
  ],
  "steps": [
    "Simmer",
    "Blend"
  ],
  "tags": [
    "soup",
    "healthy",
    "vegan"
  ]
}

### Delete recipe with id=19
DELETE http://localhost:3000/api/recipes/d210d680-cb30-46f2-9ed8-5e5f0714d7fc

### Signup
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "email": "muhammed@example.com",
  "password": "password$"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "heba@example.com",
  "password": "password"
}

### Login with invalid email
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "heb@example.com",
  "password": "password"
}

### Login with invalid password
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "heb@example.com",
  "password": "invalid-password"
}

### Get current authenticated user
GET http://localhost:3000/api/auth/me
Authorization: Bearer YOUR_TOKEN